[package]
name = "crypto"
version = "0.1.0"
authors = ["Alexander Jackson <alexanderjackson@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
rand = "0.7.3"
rsa = { git = "https://github.com/RustCrypto/RSA", features = ["pem"] }
