version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    expose:
      - 3000
    ports:
      - "3000:3000"
    stdin_open: true
    command: yarn start
    links:
      - api-server

  api-server:
    image: 'rust:latest'
    build: ./api-server
    expose:
      - 3001
    ports: 
      - "3001:3001"
    volumes:
      - ./api-server:/usr/src/app
    working_dir: /usr/src/app
    command: cargo watch -c -x run
    # command: 
    #   - rustc --version
    #   - cargo watch -c -x run
        


# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
