version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    stdin_open: true
    command: yarn start
    links:
      - api_server

  api_server:
    environment:
      - ROCKET_ENV=development
    build: ./api_server
    ports: 
      - "3001:3001"
    volumes:
      - ./api_server:/usr/src/app
    working_dir: /usr/src/app
    command: cargo watch -x run

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}