[package]
name = "api-server"
version = "0.1.0"
authors = ["Freddie Brown <fred@noser.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-web = "3.3.2"
actix-rt = "1.1.1"
actix-cors = "0.5.4"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pbkdf2 = "0.5.0"
env_logger = "0.7"
log = "0.4"
toml = "0.5.7"
bzip2 = "0.4.1"
csv = "1.1.3"
thiserror = "1.0.23"
chrono = "0.4"
base64 = "0.13.0"
config = { path = "../config" }
messages = { path = "../messages" }
crypto = { path = "../crypto" }
models = { path = "../models" }
utils = { path = "../utils" }

[dependencies.mongodb]
version = "1.1.0"
default-features = false
features = ["async-std-runtime"]

[dev-dependencies.futures]
version = "0.3.9"
features = ["executor"]
