# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
	"api-server",
	"analytics",
	"config",
	"dcl",
	"models",
	"utils",
	"messages"
]
