name: cargo fmt

on:
  pull_request:
    branches: [ master, develop ]
    paths:
    - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo fmt
      run: "cd backend && cargo fmt -- --check"
