name: cargo test

on:
  pull_request:
    branches: [ master, develop ]
    paths:
    - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - run: "tree && cd backend && cargo test"
