name: cargo test

on:
  pull_request:
    branches: [ master, develop ]
    paths:
    - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install latest `rustc`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1.2.0
      with:
        working-directory: "backend"

    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path backend/Cargo.toml
