name: cargo check

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cargo check
      run: "cd api-server/ && cargo check --verbose"
