name: code coverage

on:
  pull_request:
    branches: [ master, develop ]
    paths:
    - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4

    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install latest `rustc`
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        default: true

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v1.2.0
      with:
        working-directory: "backend"

    - name: Calculate code coverage
      uses: actions-rs/tarpaulin@v0.1
      with:
        args: "--manifest-path backend/Cargo.toml -- --test-threads 1"

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
